name: CI

on:
  pull_request:
    branches:
      -'*'

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  -name: Checkout Repository
   uses: actions/checkout@v2

  -name: Setup Node.js
   uses: actions/set-upnode@v3
   with:
     node-version:14

  -name: Install dependencies
