name: CI

on:
  push:
    branches:
      - testdevops

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testdevops

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '15'

      - name: Install Dependencies
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm install
      - name: Lint
        working-directory: ./codebase/rdicidr-0.1.0
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: Test
        run: CI= true npn run test
      - name: build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Apply Kubernetes Secret
      run: kubectl apply -f k8/secret.yml
    - name: Apply Kubernetes Service
      run: kubectl apply -f k8/service.yml
    - name: Apply Kubernetes Deployment
      run: kubectl apply -f k8/deployment.yml
    - name: Apply Kubernetes Ingress
      run: kubectl apply -f k8/ingress.yml